[package]
cairo-version = "=2.9.4"
name = "dojo_starter"
version = "1.4.0"
edition = "2024_07"

[cairo]
sierra-replace-ids = true

[scripts]
migrate = "sozo build && sozo migrate"
spawn = "sozo execute dojo_starter-systems_action-claiming-capture_tile::capture --wait"
craft = "sozo execute dojo_starter-systems_action-claiming-craft_tile::craft --wait"
rent = "sozo execute dojo_starter-systems_action-claiming-rent_tile::collect_rent --wait"

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.4.0" }


[[target.starknet-contract]]
build-external-contracts = [
  "dojo_starter::systems_action::claiming::capture_tile",
  "dojo_starter::systems_action::claiming::craft_tile",
  "dojo_starter::systems_action::claiming::rent_tile"
]
